# Generated by Django 5.0.4 on 2025-10-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_alter_category_options_alter_chat_options_and_more"),
        ("services", "0003_service_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created"],
                "verbose_name": "послуга",
                "verbose_name_plural": "послуги",
            },
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                help_text="Категорія, в якій буде розміщено послугу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="exchange.category",
                verbose_name="рубрика",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="створена"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                help_text="Детальний опис послуги, що надається",
                max_length=1200,
                verbose_name="опис",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/services/",
                verbose_name="обкладинка",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Зніміть галочку, щоб виключити послугу з каталогу, не видаляючи її.",
                verbose_name="послуга активна",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="options",
            field=models.TextField(
                blank=True,
                help_text="Якщо ви пропонуєте додаткові послуги, розкажіть про них. Вкажіть назву, термін, вартість.",
                max_length=1200,
                null=True,
                verbose_name="додаткові послуги",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="portfolio_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="посилання на портфоліо"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.IntegerField(
                help_text="Вартість послуги в грн.", verbose_name="вартість"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                help_text="Користувач, який надає дану послугу",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
                verbose_name="виконавець послуги",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="requirements",
            field=models.TextField(
                help_text="Вкажіть що потрібно від замовника послуги. Наприклад, ТЗ, доступи тощо.",
                max_length=500,
                verbose_name="від покупця потрібно",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="term",
            field=models.IntegerField(
                help_text="Термін виконання послуги, в днях", verbose_name="термін"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=70, verbose_name="назва"),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="змінена"),
        ),
    ]
