version: "3.9"
services:
  web:
    container_name: "web"
    build: ./src
    command: python -m manage runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    environment:
      - "DEBUG=True"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5432"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: "db"
    image: postgres:16
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
    container_name: "redis"
    image: redis:7.2.4
    volumes:
      - ./docker/redis:/data
  worker:
    container_name: "worker"
    build: ./src
    volumes:
      - ./src:/code
    command: ['celery', '--workdir=/code', '-A', 'django_project', 'worker']
    environment:
      - "DEBUG=True"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=db"
      - "DB_PORT=5432"
