# Generated by Django 5.0.4 on 2025-10-21 12:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["id"],
                "verbose_name": "користувач",
                "verbose_name_plural": "користувачі",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="car_owner",
            field=models.BooleanField(
                default=False, verbose_name="є власний автомобіль"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employee", "Найманий працівник"),
                    ("self_employed", "Самозайнятий/ФОП"),
                    ("student", "Студент"),
                    ("parent", "Батько/Мати в декреті"),
                    ("retired", "На пенсії"),
                    ("unemployed", "Тимчасово без роботи"),
                ],
                max_length=20,
                null=True,
                verbose_name="зайнятість",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_children",
            field=models.BooleanField(
                default=False,
                help_text="Позначте, якщо у вашій сім'ї є діти",
                verbose_name="є діти",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_pets",
            field=models.BooleanField(
                default=False,
                help_text="Позначте, якщо у вас є домашні тварини",
                verbose_name="є домашні тварини",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Квартира"),
                    ("house", "Будинок"),
                    ("other", "Інше"),
                ],
                max_length=20,
                null=True,
                verbose_name="тип житла",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="prefer_online_services",
            field=models.BooleanField(
                default=True, verbose_name="надаю перевагу онлайн послугам"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="questionnaire_completed",
            field=models.BooleanField(default=False, verbose_name="анкету заповнено"),
        ),
        migrations.AlterField(
            model_name="action",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="користувач",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="місто"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="країна"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1200,
                null=True,
                verbose_name="інформація про вас і ваш досвід",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Номер телефону у форматі +380(00)000-00-00",
                max_length=64,
                null=True,
                verbose_name="телефон",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/profiles/",
                verbose_name="зображення профілю",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="skills",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                help_text="Список ваших навичок через кому",
                null=True,
                size=None,
                verbose_name="ваші навички",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="speciality",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ви за спеціальністю"
            ),
        ),
    ]
