# Generated by Django 5.0.4 on 2025-10-21 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options_customuser_car_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailedQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "household_adults",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Дорослих у домогосподарстві"
                    ),
                ),
                (
                    "household_children",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Дітей у домогосподарстві"
                    ),
                ),
                (
                    "has_infants",
                    models.BooleanField(default=False, verbose_name="Є немовлята"),
                ),
                (
                    "pets_dogs",
                    models.BooleanField(default=False, verbose_name="Є собаки"),
                ),
                (
                    "pets_cats",
                    models.BooleanField(default=False, verbose_name="Є коти"),
                ),
                (
                    "pets_other",
                    models.BooleanField(default=False, verbose_name="Інші тварини"),
                ),
                (
                    "dwelling_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Квартира"),
                            ("house", "Будинок"),
                            ("other", "Інше"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="Тип житла",
                    ),
                ),
                (
                    "dwelling_rooms",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Кімнат"),
                ),
                (
                    "dwelling_area",
                    models.PositiveIntegerField(
                        default=40, verbose_name="Площа (кв.м)"
                    ),
                ),
                (
                    "has_garden",
                    models.BooleanField(default=False, verbose_name="Є подвір'я/сад"),
                ),
                (
                    "car_owner",
                    models.BooleanField(default=False, verbose_name="Є авто"),
                ),
                (
                    "bike_owner",
                    models.BooleanField(
                        default=False, verbose_name="Є велосипед/електросамокат"
                    ),
                ),
                (
                    "availability_weekdays",
                    models.BooleanField(default=True, verbose_name="Доступний у будні"),
                ),
                (
                    "availability_weekends",
                    models.BooleanField(
                        default=False, verbose_name="Доступний у вихідні"
                    ),
                ),
                (
                    "availability_evenings",
                    models.BooleanField(
                        default=False, verbose_name="Доступний ввечері"
                    ),
                ),
                (
                    "budget_min",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Мінімальний бюджет (грн)"
                    ),
                ),
                (
                    "budget_max",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимальний бюджет (грн)"
                    ),
                ),
                (
                    "language_uk",
                    models.BooleanField(default=True, verbose_name="Українська"),
                ),
                (
                    "language_ru",
                    models.BooleanField(default=False, verbose_name="Російська"),
                ),
                (
                    "language_en",
                    models.BooleanField(default=False, verbose_name="Англійська"),
                ),
                (
                    "language_other",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Інші мови"
                    ),
                ),
                (
                    "interested_home",
                    models.BooleanField(
                        default=False,
                        verbose_name="Домашні послуги (прибирання, ремонт)",
                    ),
                ),
                (
                    "interested_children",
                    models.BooleanField(
                        default=False, verbose_name="Діти/догляд/репетитори"
                    ),
                ),
                (
                    "interested_pets",
                    models.BooleanField(default=False, verbose_name="Тварини"),
                ),
                (
                    "interested_auto",
                    models.BooleanField(default=False, verbose_name="Авто"),
                ),
                (
                    "interested_it",
                    models.BooleanField(
                        default=False, verbose_name="IT/розробка/дизайн"
                    ),
                ),
                (
                    "interested_marketing",
                    models.BooleanField(
                        default=False, verbose_name="Маркетинг/копірайт"
                    ),
                ),
                (
                    "interested_translation",
                    models.BooleanField(default=False, verbose_name="Переклад"),
                ),
                (
                    "interested_admin",
                    models.BooleanField(
                        default=False, verbose_name="Адміністрування/підтримка"
                    ),
                ),
                (
                    "prefer_online",
                    models.BooleanField(
                        default=True, verbose_name="Переважно онлайн-послуги"
                    ),
                ),
                (
                    "prefer_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Хочу бачити лише перевірених виконавців",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Побажання/деталі"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "детальна анкета",
                "verbose_name_plural": "детальні анкети",
            },
        ),
    ]
