# Generated by Django 5.0.4 on 2025-10-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0003_alter_category_options_alter_chat_options_and_more"),
        ("projects", "0003_offer_is_cancelled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created"],
                "verbose_name": "проєкт",
                "verbose_name_plural": "проєкти",
            },
        ),
        migrations.AlterField(
            model_name="offer",
            name="candidate",
            field=models.ForeignKey(
                help_text="Пользователь, который предлагает свои послуги для реализации проєкта.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кандидат на выполнение проєкта",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Коментар кандидата для замовника касательно проєкта.",
                max_length=500,
                null=True,
                verbose_name="комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="створено"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Предложение скасованоо или отклонено.",
                verbose_name="скасованоо",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="projects.project",
                verbose_name="проєкт",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Створено кандидатом"),
                    ("declined", "Відхилено замовником"),
                    ("cancelled", "Скасовано кандидатом"),
                    ("accepted", "Прийнято замовником"),
                ],
                default="created",
                max_length=32,
                verbose_name="статус предложения",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="змінено"),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                help_text="Категорія, в якій буде розміщено проєкт",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="exchange.category",
                verbose_name="рубрика",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="створено"),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                help_text="Користувач, який пропонує даний проєкт для реалізації",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="замовник проєкту",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                help_text="Опишіть, що саме вам потрібно, в якому обсязі і за який термін.",
                max_length=5200,
                verbose_name="детальний опис завдання",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Зніміть галочку, щоб виключити проєкт з каталогу, не видаляючи його.",
                verbose_name="проєкт активний",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_higher_price_allowed",
            field=models.BooleanField(
                default=False,
                verbose_name="Готовий розглянути пропозиції з ціною вище, якщо рівень виконавця буде вищим",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_price",
            field=models.IntegerField(
                blank=True,
                help_text="Максимальна ціна у разі високого рівня виконавця.",
                null=True,
                verbose_name="максимальна ціна",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="price",
            field=models.IntegerField(
                help_text="Ваш бюджет в грн.", verbose_name="ціна не більше"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=70, verbose_name="назва"),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="змінено"),
        ),
    ]
