# Generated by Django 5.0.4 on 2025-10-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created"],
                "verbose_name": "замовлення",
                "verbose_name_plural": "замовлення",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True,
                max_length=1500,
                null=True,
                verbose_name="коментар до замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="створено"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="замовник",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="скасовано"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="завершено"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="оплачено"),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(
                help_text="Вартість замовлення в грн.", verbose_name="вартість"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_provider",
                to=settings.AUTH_USER_MODEL,
                verbose_name="виконавець",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Розміщено замовником"),
                    ("in_progress", "В роботі у виконавця"),
                    ("cancelled_by_customer", "Скасовано замовником"),
                    ("rejected_by_provider", "Відхилено виконавцем"),
                    ("submitted_by_provider", "Здано виконавцем"),
                    ("returned_by_customer", "Повернуто замовником на доопрацювання"),
                    ("accepted_by_customer", "Прийнято замовником"),
                    ("paid", "Оплачено"),
                    ("completed", "Завершено"),
                ],
                default="created",
                max_length=32,
                verbose_name="статус замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="оновлено"),
        ),
    ]
