# Generated by Django 5.0.4 on 2025-10-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_chat_message_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "категорія",
                "verbose_name_plural": "категорії",
            },
        ),
        migrations.AlterModelOptions(
            name="chat",
            options={
                "ordering": ["-created"],
                "verbose_name": "чат",
                "verbose_name_plural": "чати",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created"],
                "verbose_name": "cообщение",
                "verbose_name_plural": "повідомлення",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="exchange.category",
                verbose_name="батьківська категорія",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=70, verbose_name="назва"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="створено"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="latest_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_in_chat",
                to="exchange.message",
                verbose_name="Останнє повідомлення",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="змінено"),
        ),
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="створеноо"),
        ),
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Файл, прилагаемый к сообщению.",
                null=True,
                upload_to="attachments/",
                verbose_name="вложение",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="Повідомлення прочитано получателем.",
                verbose_name="прочитано",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="отримувач",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="відправник",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(max_length=1500, verbose_name="Текст повідомлення"),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="зміненоо"),
        ),
        migrations.CreateModel(
            name="CategoryProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="назва")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="опис/обґрунтування"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "прийнято на модерацію"),
                            ("approved", "схвалено"),
                            ("rejected", "відхилено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exchange.category",
                        verbose_name="батьківська категорія",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "запропонована категорія",
                "verbose_name_plural": "запропоновані категорії",
                "ordering": ["-created"],
            },
        ),
    ]
